SPK_NAME = mono
SPK_VERS = 3.4.0
SPK_REV = 1
SPK_ICON = src/mono.png
DSM_UI_DIR = app

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = Cross platform, open source .NET development framework
DISPLAY_NAME = Mono
CHANGELOG = "1. Initial release"

HOMEPAGE = http://mono-project.com/
LICENSE  =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk

